export type Listing = {
  id: number;
  title: string;
  host: string;
  hostInitials: string;
  hostColor: string;
  price: number;
  rating: number;
  reviews: number;
  lat: number;
  lng: number;
  neighborhood: string;
  city: string;
  environment: "Familia con hijos" | "Pareja" | "Persona sola" | "Vivo solo/a";
  available: boolean;
  verified: boolean;
  amenities: string[];
  description: string;
  // --- Paso 1: Ritmo de vida ---
  hostSchedule: "manana" | "noche" | "flexible" | "home-office";
  hostDaysHome: "pocos" | "mitad" | "casi-siempre";
  // --- Paso 2: Convivencia diaria ---
  hostNoise: "muy-tranquilo" | "normal" | "social";
  hostKitchenUse: "raramente" | "cocino-seguido" | "meal-prep";
  hostCommonTemp: "frio" | "templado" | "calido";
  hostBathroomTime: "rapido" | "normal" | "largo";
  // --- Paso 3: Habitos ---
  hostPets: "no" | "si-pequena" | "si-grande" | "acepta";
  hostSmoking: "no" | "afuera" | "si";
  hostAlcohol: "no" | "social" | "frecuente";
  hostCleanliness: "muy-ordenado" | "normal" | "relajado";
  hostVisits: "casi-nunca" | "a-veces" | "seguido";
  hostOvernightGuests: "no" | "a-veces" | "si";
  // --- Paso 4: Perfil social ---
  hostPersonality: "introvertido" | "ambivertido" | "extrovertido";
  hostConflictStyle: "hablar-directo" | "escrito" | "evitar";
  hostCohabitation: "independencia-total" | "cordial" | "convivir";
  // --- Paso 5: Busqueda ---
  hostOccupation: "estudiante" | "profesional" | "sin-preferencia";
  hostRoommateGender: "sin-preferencia" | "mismo-genero" | "cualquiera";
};

export const mockListings: Listing[] = [
  {
    id: 1,
    title: "Habitaci\u00f3n amplia con ba\u00f1o privado",
    host: "Carmen L\u00f3pez",
    hostInitials: "CL",
    hostColor: "#D85A30",
    price: 220,
    rating: 4.8,
    reviews: 14,
    lat: 13.7034,
    lng: -89.224,
    neighborhood: "Colonia Escal\u00f3n",
    city: "San Salvador",
    environment: "Familia con hijos",
    available: true,
    verified: true,
    amenities: ["WiFi", "Agua caliente", "Cocina compartida"],
    description: "Cuarto c\u00f3modo en casa familiar, tranquilo, con acceso a sala y jard\u00edn.",
    hostSchedule: "manana",
    hostDaysHome: "mitad",
    hostNoise: "muy-tranquilo",
    hostKitchenUse: "cocino-seguido",
    hostCommonTemp: "templado",
    hostBathroomTime: "rapido",
    hostPets: "no",
    hostSmoking: "no",
    hostAlcohol: "no",
    hostCleanliness: "muy-ordenado",
    hostVisits: "casi-nunca",
    hostOvernightGuests: "no",
    hostPersonality: "introvertido",
    hostConflictStyle: "hablar-directo",
    hostCohabitation: "cordial",
    hostOccupation: "profesional",
    hostRoommateGender: "sin-preferencia",
  },
  {
    id: 2,
    title: "Cuarto soleado en zona c\u00e9ntrica",
    host: "Roberto M\u00e9ndez",
    hostInitials: "RM",
    hostColor: "#2a7a6a",
    price: 180,
    rating: 4.5,
    reviews: 9,
    lat: 13.698,
    lng: -89.218,
    neighborhood: "Centro Hist\u00f3rico",
    city: "San Salvador",
    environment: "Persona sola",
    available: true,
    verified: true,
    amenities: ["WiFi", "Estacionamiento", "Aire acondicionado"],
    description: "Excelente ubicaci\u00f3n, a dos cuadras del parque central.",
    hostSchedule: "flexible",
    hostDaysHome: "casi-siempre",
    hostNoise: "normal",
    hostKitchenUse: "raramente",
    hostCommonTemp: "templado",
    hostBathroomTime: "normal",
    hostPets: "acepta",
    hostSmoking: "afuera",
    hostAlcohol: "social",
    hostCleanliness: "normal",
    hostVisits: "a-veces",
    hostOvernightGuests: "a-veces",
    hostPersonality: "ambivertido",
    hostConflictStyle: "hablar-directo",
    hostCohabitation: "convivir",
    hostOccupation: "sin-preferencia",
    hostRoommateGender: "cualquiera",
  },
  {
    id: 3,
    title: "Habitaci\u00f3n en casa de pareja tranquila",
    host: "Ana y Luis Flores",
    hostInitials: "AF",
    hostColor: "#7a4a8a",
    price: 250,
    rating: 4.9,
    reviews: 22,
    lat: 13.6875,
    lng: -89.2415,
    neighborhood: "Antiguo Cusc\u00e1tlan",
    city: "Antiguo Cusc\u00e1tlan",
    environment: "Pareja",
    available: true,
    verified: true,
    amenities: ["WiFi", "Agua caliente", "Lavander\u00eda", "Jard\u00edn"],
    description: "Casa moderna, silenciosa, ideal para estudiantes o profesionales.",
    hostSchedule: "manana",
    hostDaysHome: "mitad",
    hostNoise: "muy-tranquilo",
    hostKitchenUse: "meal-prep",
    hostCommonTemp: "frio",
    hostBathroomTime: "normal",
    hostPets: "si-pequena",
    hostSmoking: "no",
    hostAlcohol: "no",
    hostCleanliness: "muy-ordenado",
    hostVisits: "casi-nunca",
    hostOvernightGuests: "no",
    hostPersonality: "introvertido",
    hostConflictStyle: "escrito",
    hostCohabitation: "independencia-total",
    hostOccupation: "estudiante",
    hostRoommateGender: "mismo-genero",
  },
  {
    id: 4,
    title: "Cuarto independiente con entrada propia",
    host: "Mario Guti\u00e9rrez",
    hostInitials: "MG",
    hostColor: "#3a6a9a",
    price: 195,
    rating: 4.3,
    reviews: 6,
    lat: 13.7095,
    lng: -89.2355,
    neighborhood: "Santa Elena",
    city: "Antiguo Cusc\u00e1tlan",
    environment: "Vivo solo/a",
    available: false,
    verified: true,
    amenities: ["WiFi", "Ba\u00f1o privado", "Cocina compartida"],
    description: "Habitaci\u00f3n con entrada independiente, total privacidad.",
    hostSchedule: "home-office",
    hostDaysHome: "casi-siempre",
    hostNoise: "normal",
    hostKitchenUse: "cocino-seguido",
    hostCommonTemp: "templado",
    hostBathroomTime: "rapido",
    hostPets: "no",
    hostSmoking: "no",
    hostAlcohol: "no",
    hostCleanliness: "muy-ordenado",
    hostVisits: "a-veces",
    hostOvernightGuests: "a-veces",
    hostPersonality: "introvertido",
    hostConflictStyle: "hablar-directo",
    hostCohabitation: "independencia-total",
    hostOccupation: "profesional",
    hostRoommateGender: "cualquiera",
  },
  {
    id: 5,
    title: "Habitaci\u00f3n luminosa cerca de UTEC",
    host: "Patricia V\u00e1squez",
    hostInitials: "PV",
    hostColor: "#8a6a2a",
    price: 160,
    rating: 4.6,
    reviews: 11,
    lat: 13.7012,
    lng: -89.2098,
    neighborhood: "Colonia M\u00e9dica",
    city: "San Salvador",
    environment: "Persona sola",
    available: true,
    verified: false,
    amenities: ["WiFi", "Agua caliente"],
    description: "A cinco minutos de la UTEC, zona segura y bien conectada.",
    hostSchedule: "noche",
    hostDaysHome: "pocos",
    hostNoise: "social",
    hostKitchenUse: "raramente",
    hostCommonTemp: "calido",
    hostBathroomTime: "largo",
    hostPets: "acepta",
    hostSmoking: "afuera",
    hostAlcohol: "social",
    hostCleanliness: "relajado",
    hostVisits: "seguido",
    hostOvernightGuests: "si",
    hostPersonality: "extrovertido",
    hostConflictStyle: "evitar",
    hostCohabitation: "convivir",
    hostOccupation: "estudiante",
    hostRoommateGender: "sin-preferencia",
  },
  {
    id: 6,
    title: "Cuarto en casa familiar con ni\u00f1os",
    host: "Sonia Hern\u00e1ndez",
    hostInitials: "SH",
    hostColor: "#c04f28",
    price: 200,
    rating: 4.7,
    reviews: 18,
    lat: 13.7156,
    lng: -89.2188,
    neighborhood: "Colonia San Benito",
    city: "San Salvador",
    environment: "Familia con hijos",
    available: true,
    verified: true,
    amenities: ["WiFi", "Comidas incluidas", "Agua caliente", "Jard\u00edn"],
    description: "Familia acogedora, ambiente seguro y hoga\u00f1o. Incluye desayuno y cena.",
    hostSchedule: "manana",
    hostDaysHome: "casi-siempre",
    hostNoise: "normal",
    hostKitchenUse: "cocino-seguido",
    hostCommonTemp: "calido",
    hostBathroomTime: "normal",
    hostPets: "si-pequena",
    hostSmoking: "no",
    hostAlcohol: "no",
    hostCleanliness: "normal",
    hostVisits: "casi-nunca",
    hostOvernightGuests: "no",
    hostPersonality: "ambivertido",
    hostConflictStyle: "hablar-directo",
    hostCohabitation: "cordial",
    hostOccupation: "sin-preferencia",
    hostRoommateGender: "mismo-genero",
  },
  {
    id: 7,
    title: "Habitaci\u00f3n moderna en residencial privada",
    host: "Diego Alvarado",
    hostInitials: "DA",
    hostColor: "#2a6a4a",
    price: 280,
    rating: 4.4,
    reviews: 5,
    lat: 13.6812,
    lng: -89.2498,
    neighborhood: "Las Colinas",
    city: "Antiguo Cusc\u00e1tlan",
    environment: "Pareja",
    available: true,
    verified: true,
    amenities: ["WiFi", "Piscina", "Gimnasio", "Estacionamiento", "Aire acondicionado"],
    description: "Residencial con vigilancia 24h, acceso a amenidades exclusivas.",
    hostSchedule: "home-office",
    hostDaysHome: "casi-siempre",
    hostNoise: "muy-tranquilo",
    hostKitchenUse: "meal-prep",
    hostCommonTemp: "frio",
    hostBathroomTime: "rapido",
    hostPets: "no",
    hostSmoking: "no",
    hostAlcohol: "no",
    hostCleanliness: "muy-ordenado",
    hostVisits: "casi-nunca",
    hostOvernightGuests: "a-veces",
    hostPersonality: "introvertido",
    hostConflictStyle: "escrito",
    hostCohabitation: "independencia-total",
    hostOccupation: "profesional",
    hostRoommateGender: "cualquiera",
  },
  {
    id: 8,
    title: "Cuarto econ\u00f3mico cerca de plaza",
    host: "Elena Ramos",
    hostInitials: "ER",
    hostColor: "#6a2a7a",
    price: 140,
    rating: 4.1,
    reviews: 3,
    lat: 13.6945,
    lng: -89.2305,
    neighborhood: "Barrio San Jacinto",
    city: "San Salvador",
    environment: "Vivo solo/a",
    available: false,
    verified: false,
    amenities: ["WiFi", "Cocina compartida"],
    description: "Opci\u00f3n econ\u00f3mica, zona comercial, cerca de rutas de bus.",
    hostSchedule: "noche",
    hostDaysHome: "pocos",
    hostNoise: "social",
    hostKitchenUse: "raramente",
    hostCommonTemp: "calido",
    hostBathroomTime: "largo",
    hostPets: "acepta",
    hostSmoking: "si",
    hostAlcohol: "frecuente",
    hostCleanliness: "relajado",
    hostVisits: "seguido",
    hostOvernightGuests: "si",
    hostPersonality: "extrovertido",
    hostConflictStyle: "evitar",
    hostCohabitation: "convivir",
    hostOccupation: "estudiante",
    hostRoommateGender: "sin-preferencia",
  },
];
