export type Listing = {
  id: number;
  title: string;
  host: string;
  hostInitials: string;
  hostColor: string;
  price: number;
  rating: number;
  reviews: number;
  lat: number;
  lng: number;
  neighborhood: string;
  city: string;
  environment: "Familia con hijos" | "Pareja" | "Persona sola" | "Vivo solo/a";
  available: boolean;
  verified: boolean;
  amenities: string[];
  description: string;
};

export const mockListings: Listing[] = [
  {
    id: 1,
    title: "Habitación amplia con baño privado",
    host: "Carmen López",
    hostInitials: "CL",
    hostColor: "#D85A30",
    price: 220,
    rating: 4.8,
    reviews: 14,
    lat: 13.7034,
    lng: -89.224,
    neighborhood: "Colonia Escalón",
    city: "San Salvador",
    environment: "Familia con hijos",
    available: true,
    verified: true,
    amenities: ["WiFi", "Agua caliente", "Cocina compartida"],
    description:
      "Cuarto cómodo en casa familiar, tranquilo, con acceso a sala y jardín.",
  },
  {
    id: 2,
    title: "Cuarto soleado en zona céntrica",
    host: "Roberto Méndez",
    hostInitials: "RM",
    hostColor: "#2a7a6a",
    price: 180,
    rating: 4.5,
    reviews: 9,
    lat: 13.698,
    lng: -89.218,
    neighborhood: "Centro Histórico",
    city: "San Salvador",
    environment: "Persona sola",
    available: true,
    verified: true,
    amenities: ["WiFi", "Estacionamiento", "Aire acondicionado"],
    description: "Excelente ubicación, a dos cuadras del parque central.",
  },
  {
    id: 3,
    title: "Habitación en casa de pareja tranquila",
    host: "Ana y Luis Flores",
    hostInitials: "AF",
    hostColor: "#7a4a8a",
    price: 250,
    rating: 4.9,
    reviews: 22,
    lat: 13.6875,
    lng: -89.2415,
    neighborhood: "Antiguo Cuscatlán",
    city: "Antiguo Cuscatlán",
    environment: "Pareja",
    available: true,
    verified: true,
    amenities: ["WiFi", "Agua caliente", "Lavandería", "Jardín"],
    description: "Casa moderna, silenciosa, ideal para estudiantes o profesionales.",
  },
  {
    id: 4,
    title: "Cuarto independiente con entrada propia",
    host: "Mario Gutiérrez",
    hostInitials: "MG",
    hostColor: "#3a6a9a",
    price: 195,
    rating: 4.3,
    reviews: 6,
    lat: 13.7095,
    lng: -89.2355,
    neighborhood: "Santa Elena",
    city: "Antiguo Cuscatlán",
    environment: "Vivo solo/a",
    available: false,
    verified: true,
    amenities: ["WiFi", "Baño privado", "Cocina compartida"],
    description: "Habitación con entrada independiente, total privacidad.",
  },
  {
    id: 5,
    title: "Habitación luminosa cerca de UTEC",
    host: "Patricia Vásquez",
    hostInitials: "PV",
    hostColor: "#8a6a2a",
    price: 160,
    rating: 4.6,
    reviews: 11,
    lat: 13.7012,
    lng: -89.2098,
    neighborhood: "Colonia Médica",
    city: "San Salvador",
    environment: "Persona sola",
    available: true,
    verified: false,
    amenities: ["WiFi", "Agua caliente"],
    description: "A cinco minutos de la UTEC, zona segura y bien conectada.",
  },
  {
    id: 6,
    title: "Cuarto en casa familiar con niños",
    host: "Sonia Hernández",
    hostInitials: "SH",
    hostColor: "#c04f28",
    price: 200,
    rating: 4.7,
    reviews: 18,
    lat: 13.7156,
    lng: -89.2188,
    neighborhood: "Colonia San Benito",
    city: "San Salvador",
    environment: "Familia con hijos",
    available: true,
    verified: true,
    amenities: ["WiFi", "Comidas incluidas", "Agua caliente", "Jardín"],
    description:
      "Familia acogedora, ambiente seguro y hogareño. Incluye desayuno y cena.",
  },
  {
    id: 7,
    title: "Habitación moderna en residencial privada",
    host: "Diego Alvarado",
    hostInitials: "DA",
    hostColor: "#2a6a4a",
    price: 280,
    rating: 4.4,
    reviews: 5,
    lat: 13.6812,
    lng: -89.2498,
    neighborhood: "Las Colinas",
    city: "Antiguo Cuscatlán",
    environment: "Pareja",
    available: true,
    verified: true,
    amenities: [
      "WiFi",
      "Piscina",
      "Gimnasio",
      "Estacionamiento",
      "Aire acondicionado",
    ],
    description:
      "Residencial con vigilancia 24h, acceso a amenidades exclusivas.",
  },
  {
    id: 8,
    title: "Cuarto económico cerca de plaza",
    host: "Elena Ramos",
    hostInitials: "ER",
    hostColor: "#6a2a7a",
    price: 140,
    rating: 4.1,
    reviews: 3,
    lat: 13.6945,
    lng: -89.2305,
    neighborhood: "Barrio San Jacinto",
    city: "San Salvador",
    environment: "Vivo solo/a",
    available: false,
    verified: false,
    amenities: ["WiFi", "Cocina compartida"],
    description: "Opción económica, zona comercial, cerca de rutas de bus.",
  },
];
